import os
import urllib.request
import xml.etree.ElementTree as ET
import re
import time
from datetime import datetime
from google import genai

# 1. Fetch the RSS feed
url = "https://timesofindia.indiatimes.com/rssfeedstopstories.cms"
req = urllib.request.Request(url, headers={'User-Agent': 'Mozilla/5.0'})
response = urllib.request.urlopen(req).read()
root = ET.fromstring(response)

# 2. Get the TOP 2 articles from the feed (will give you 4 daily posts total)
items = root.findall('.//item')[:2]

client = genai.Client(api_key=os.environ["GEMINI_API_KEY"])
date_str = datetime.now().strftime("%Y-%m-%d")
os.makedirs("_posts", exist_ok=True)

# 3. Loop through each of the 2 articles
for item in items:
    topic = item.find('title').text
    
    # Define keywords for the image fetcher
    # Use topic words to generate a generic image relevant to India and the news
    image_keywords = f"india,{topic.replace(' ', ',').lower()}"
    image_url = f"https://source.unsplash.com/1200x800/?{image_keywords}"

    # Generate the article with the new specific structure
    prompt = f"""
    Create a comprehensive, factual, and informative blog post in Markdown format about this trending news topic: {topic}.

    Use this exact structure for the output:

    1.  Start with a section title: "Quick Summary". Write a brief, bulleted 2-3 sentence overview of the key facts (a "TL;DR").
    2.  Embed a relevant stock image using this exact Markdown syntax: `![Image related to {topic}]({image_url})`
    3.  Create a section title: "Detailed Update".
    4.  Write a detailed, informative article on the topic. It must be at least 500-600 words long. Use multiple paragraphs, provide background context, and use relevant subheadings to make it easy to read.
    5.  Remain entirely factual, neutral, and unbiased. Do not take sides or add personal opinions.
    """
    
    try:
        response = client.models.generate_content(
            model='gemini-2.5-flash',
            contents=prompt,
        )
        
        # Create a safe file name (YEAR-MONTH-DAY-title.md)
        safe_title = re.sub(r'[^a-zA-Z0-9]', '-', topic).lower()
        safe_title = re.sub(r'-+', '-', safe_title).strip('-')
        filename = f"_posts/{date_str}-{safe_title}.md"
        
        # Save the file
        with open(filename, "w", encoding="utf-8") as f:
            f.write("---\n")
            f.write("layout: post\n")  # Keeps the beautiful article layout
            f.write(f"title: \"{topic}\"\n")
            f.write("---\n\n")
            # Write the article text generated by Gemini (which includes summary, image embed, and detail)
            f.write(response.text)
            
    except Exception as e:
        print(f"Failed to generate {topic}: {e}")
        
    # Pause for 5 seconds to respect Gemini's free-tier rate limits
    time.sleep(5)
